name: "supplysync_dbt"
version: "1.0.0"
config-version: 2

profile: "supplysync_dbt"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  supplysync_dbt:
    +materialized: table
    marts:
      +materialized: table
